---
ansible_ssh_user: vagrant 
exports:
  - /mnt/warm *(rw,sync,no_subtree_check,no_root_squash)
  - /mnt/hot *(rw,sync,no_subtree_check,no_root_squash)
mounts:
  - path: /mnt/warm 
    src: tmpfs
    fstype: tmpfs
    opts: "size=512m"
    state: mounted
  - path: /mnt/hot 
    src: tmpfs
    fstype: tmpfs
    opts: "size=512m"
    state: mounted