---
exports:
  - /mnt/warm 192.168.50.0/24(rw,sync,no_subtree_check,no_root_squash)
  - /mnt/hot 192.168.50.0/24(rw,sync,no_subtree_check,no_root_squash)
mounts:
#  - path: /mnt/warm 
#    src: /dev/md/nas:warm
#    fstype: xfs
#    opts: "rw,noatime"
#    state: present
#  - path: /mnt/hot 
#    src: /dev/md/nas:hot
#    fstype: xfs
#    opts: "rw,noatime"
#    state: present