---
ansible_ssh_user: vagrant
exports: []
mounts:
  - path: /mnt/warm
    src: nas.local:/mnt/warm
    fstype: nfs
    opts: "auto,nofail,noatime,nolock,intr,tcp,actimeo=1800"
    state: mounted
  - path: /mnt/hot
    src: nas.local:/mnt/hot
    fstype: nfs
    opts: "auto,nofail,noatime,nolock,intr,tcp,actimeo=1800"
    state: mounted