---
# defaults file for kube
kube_packages:
  - containerd.io
  - "kubeadm-{{ kube.version }}"
  - "kubectl-{{ kube.version }}"
  - "kubelet-{{ kube.version }}"
kube_ports:
  - 6443/tcp # kube-apiserver
  - 2379-2380/tcp # kube-etcd
  - 10250-10252/tcp # kubelet
